Author: BEDEZUB
Date: 2021-08-12
Title: Numpy Ultraquick
Objective: To understand how numpy works

In [2]:
# Numpy installation - Uncomment line below or Run the requirements.txt
# !pip install numpy

     |████████████████████████████████| 15.8 MB 1.8 MB/s 


In [3]:
import numpy as np

In [4]:
# Create a one dimension array
one_dimension_array = np.array([1.2, 1.3, 1.4, 1.5])
print(one_dimension_array)

[1.2 1.3 1.4 1.5]


In [7]:
# Create a two dimension array
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [12]:
# Populate a matrix with all zeros
zeros_array = np.zeros(shape=(2,2))
print(zeros_array)

[[0. 0.]
 [0. 0.]]


In [14]:
# Populate a matrix with all ones
ones_array = np.ones(shape=(2,2))
print(ones_array)

[[1. 1.]
 [1. 1.]]


In [16]:
# Populate an array with sequence of integers
sequence_array = np.arange(start=5, stop=50, step=5)
print(sequence_array)

[ 5 10 15 20 25 30 35 40 45]


In [18]:
# Create random integers
random_array = np.random.randint(low=50, high=100, size=(10))
print(random_array)

[91 60 79 78 93 85 77 77 73 73]


In [22]:
# Mathematical Operation on Numpy. This is the fun part
print("-------- Original array -------")
print(sequence_array)

print("\n------ Original array + 2 -----")
sequence_array_plus_2 = sequence_array + 2
print(sequence_array_plus_2)

-------- Original array -------
[ 5 10 15 20 25 30 35 40 45]

------ Original array + 2 -----
[ 7 12 17 22 27 32 37 42 47]


In [25]:
## Task 1: Create a Linear Dataset

# Assign a sequence of integers from 6 to 20 to a NumPy array named feature
feature = np.arange(start=6, stop=20)
print(feature)

# Assign 15 values to a NumPy array named label
label = np.array((feature * 3) + 4)
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61]


In [31]:
## Task 2: Add some noise to the dataset

# Modify each value assigned to label by adding a different random floating-point value between -2 and +2
noise = (np.random.random(label.shape) * 4) - 1
print(noise)

new_label = label + noise
print(new_label)

[-0.99425478  0.08491737  2.97062852 -0.17249342  1.01823056  2.76823915
  1.82552299  0.30315391  1.33900858  2.62410345  1.61583603  2.70563462
  0.21530613 -0.73761797]
[21.00574522 25.08491737 30.97062852 30.82750658 35.01823056 39.76823915
 41.82552299 43.30315391 47.33900858 51.62410345 53.61583603 57.70563462
 58.21530613 60.26238203]
